config/routes.rb
Rails.application.routes.draw do

  devise_for :users

      resources :tweets do
        resources :comments
      end

get "/profile/:id", to: 'profile#profile', as: 'profile'
get "users", to: 'myuser#userList', as: 'myusers'
get "/follow/:followed", to: "follow#follow", as: 'follow'
get "/unfollow/:followed", to: "follow#unfollow", as: 'unfollow'
get "/retweet/:post", to: "retweet#retweet", as: 'retweet'

  
  root 'tweets#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tweet
  
end

app/models/follow.rb
class Follow < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    attr_accessor :login
    
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :authentication_keys => {email: true, login: false}
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
         
         has_many :tweets, dependent: :destroy
         
         has_attached_file :avatar, :styles => { :medium => "300x300>", :small => "30x30>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  

         
    
    before_filter :configure_permitted_parameters, if: :devise_controller?

   protected
    
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :username, :avatar])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.create(comment_params)
    redirect_to tweet_path(@tweet)
  end
 
  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.find(params[:id])
    @comment.destroy
    redirect_to tweet_path(@tweet)
  end

  private
    def comment_params
      params.require(:comment).permit(:username, :body)
    end
    
end

app/controllers/follow_controller.rb
class FollowController < ApplicationController
    def follow
        @follow = Follow.create(follower: current_user.id, followed: params[:followed]) 
        if @follow.save 
          redirect_to myusers_path
        end
    end
    
    def unfollow
        @unfollow = Follow.where(:follower => current_user.id).where(:followed => params[:followed]).first
      
        @unfollow.destroy
                  redirect_to myusers_path
    end

end

app/controllers/myuser_controller.rb
class MyuserController < ApplicationController
    def userList
        @users = User.all
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    def profile
        @user = User.find(params[:id])
            @tweet = Tweet.new
            @tweets = Tweet.where("user_id = '#{@user.id}'").order('created_at DESC')
    end
end

app/controllers/retweet_controller.rb
class RetweetController < ApplicationController
    def retweet
        @retweet = Tweet.create(post: params[:post], user_id: current_user.id) 
        if @retweet.save 
          redirect_to tweets_path
        end
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order('created_at DESC').all
    @tweet = Tweet.new

  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
      
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully created.' }
        format.json { render :new, status: :created, location: tweets_path }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:post, :user_id, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/myuser_helper.rb
module MyuserHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/retweet_helper.rb
module RetweetHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-box">
    	<h2><%= comment.username %></h2>
	<p><%= comment.body %></p>
	  <%= link_to '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>'.html_safe, [comment.tweet, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' }, class: 'del-comment' %>

	<hr />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Twitter Clone', tweets_path, class: 'navbar-brand' %>
      <!--<a class="navbar-brand" href="#">Twitter Clone</a>-->
    </div>
  <% if user_signed_in? %>
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          
          <%= image_tag(current_user.avatar.url(:small)) %>

        <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li>   <%= link_to "Profile", profile_path(current_user.id) %></li>
            <li>    <%= link_to 'Members', myusers_path %></li>
           <li>   <%= link_to "Manage Account", edit_user_registration_path %></li>
            <li> <%= link_to('Logout', destroy_user_session_path, method: :delete) %>  </li>
            
            

        </ul>
      </li>
    </ul>
            <% end %>
  </div>
</nav>
<%= yield %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

app/views/myuser/userList.html.erb
<div>
        <% @users.each do |users| %>
            <%= users.email %> <%=  link_to 'Visit Profile', profile_path(users.id) %> 
            
            <% @followed = Follow.where("followed = '#{users.id}' and follower = '#{current_user.id}'").count %>
            <% 
            if users.id == current_user.id
                %><span>You</span><%
            else
                if @followed >= 1
            
             %>
             <%= link_to 'Unfollow', unfollow_path(users.id) %>
             <%
                 else 
            %>
            <%= link_to 'Follow', follow_path(users.id) %>
            <%
            end 
            
                end %> <br />
        <% end%>
    
</div>

app/views/tweets/_form.html.erb
<div class="form-group">
  <%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :post, :value => "Compose tweet here...", class: 'form-control' %>
  </div>
  <div class="field hide-field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, :value => current_user.id %>
  </div>
      <div class="form-group">
        <%= f.label :image, class: 'col-sm-3 control-label'  %>
        <div class="col-sm-6">
            <%= f.file_field :avatar%> <br />
        </div>
    </div>
    
  <div class="actions">
    <%= f.submit 'Post Tweet', class: 'submit-post form-control' %>
  </div>
<% end %>

</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<!--<p id="notice">< notice %></p>-->

<div class="container">
<div class="row">
  <div class="col-md-3">
    <div class="row">
      <div class="col-md-5">
        <%= image_tag(current_user.avatar.url(:thumb))%>
      </div>
      <div class="col-md-7">
        <span class="name"><%= current_user.name %></span><br/>
        
        <%= link_to 'View my profile', profile_path(current_user.id) %>
      </div>
  
    </div>

    <div class="row tweet-count">
              <% @my_tweet_count = Tweet.where("user_id = '#{current_user.id}'").count %>
        <% @my_followed = Follow.where("follower = '#{current_user.id}'").count %>   
         <% @my_follower = Follow.where("followed = '#{current_user.id}'").count %>  
      <div class="col-md-4">
           <p class="text-center"><%= @my_tweet_count %> <br /> TWEETS</p>
        </div>
        
        <div class="col-md-4">
                  <p class="text-center"><%= @my_followed %> <br /> FOLLOWED</p>
        </div>
        <div class="col-md-4">
        
 
     

         <p class="text-center"><%= @my_follower %> <br /> FOLLOWER</p>
      </div>
    </div>
     <br/>
    <div class="row">
      <div class="col-md-12">
         <%= render 'form' %>
      </div>
    </div>
    
    

  </div>
    <div class="col-md-7">
       
      <div class="row">
        <% @tweets.each do |tweet| %>
        <div class="col-md-12">
           <div class="row post">
             <div class="col-md-2">
               <% @user = User.find(tweet.user_id) %>
               <%= image_tag(@user.avatar.url(:thumb)) %>
            </div>
             
             <div class="col-md-10 content">
                 <span class="name"><%= @user.name %></span> <span class="username">@<%= @user.username %></span> <br />
                  <%= tweet.post %> <br />
                  <% if tweet.avatar.exists? %>
                  <%= image_tag(tweet.avatar.url(:medium)) %>
                  <% end %>
                  <span class="time-ago">
                    Posted <%= time_ago_in_words(tweet.created_at) %> ago
                  </span>
  
             
                  <div class="button">
            <% if tweet.user_id != current_user.id %>
                    <%= link_to '<span class="glyphicon glyphicon-retweet" aria-hidden="true"></span>'.html_safe, retweet_path("@#{@user.username} #{tweet.post}") %>
                    <% end %>
                    <%= link_to '<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>'.html_safe, tweet %>
                     <% if tweet.user_id == current_user.id %>
        <%= link_to '<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>'.html_safe, edit_tweet_path(tweet) %>
        
        <%= link_to '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>'.html_safe, tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
                      <% end %>
                  </div>
                   
             </div>
           </div>
        </div>
            <% end %>
      </div>
     
  </div>
    <div class="col-md-2">
    
  </div>
  
</div>

</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @tweet.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<%= render @tweet.comments %>

 <div class="add-comment">
           <h3>New Comment</h3>

        <%= form_for([@tweet, @tweet.comments.build]) do |f| %>
          <p style="display:block">
            <%= f.label :name %><br>
            <%= f.text_field :username, :value => current_user.username, class: 'text' %>
          </p>
          <p>
            <%= f.label :body %><br>
            <%= f.text_area :body, class: 'text-area' %>
          </p>
          <p>
            <%= f.submit 'Comment', class: 'btn btn-primary btn-lg button' %>
          </p>
        <% end %>
        </div>
       
       
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>